<?php

return [
    'only' => [
        'home',
        'login',
        'login.store',
        'register',
        'register.store',
        'dashboard',
        'logout',
        'verification.notice',
        'verification.verify',
        'verification.send',
        'cards.index',
        'cards.store',
        'cards.update',
        'cards.destroy',
        'cards.bulk-destroy',
        'cards.purchases',
        'purchases.index',
        'purchases.store',
        'purchases.show',
        'purchases.update',
        'purchases.destroy',
        'purchases.mark-as-paid',
        'purchases.unmark-as-paid',
        'purchases.reorder',
        'invoices.mark-as-paid',
        'invoices.unmark-as-paid',
        'preferences.update',
    ],
];
