[program:my-wallet-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /home/rodrigo-barboza/my-wallet/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=rodrigo-barboza
numprocs=2
redirect_stderr=true
stdout_logfile=/home/rodrigo-barboza/my-wallet/storage/logs/queue-worker.log
stopwaitsecs=3600

[program:my-wallet-scheduler]
command=php /home/rodrigo-barboza/my-wallet/artisan schedule:work
autostart=true
autorestart=true
user=rodrigo-barboza
redirect_stderr=true
stdout_logfile=/home/rodrigo-barboza/my-wallet/storage/logs/scheduler.log
